name: Deploy to Cloud Run

on:
  push:
    branches:
      - main  # Or your main branch name

env:
  PROJECT_ID: "premium-state-449406-n8"
  REGION: "us-east1"
  SERVICE_ACCOUNT_NAME: "gh-cicd-agent"

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ env.PROJECT_ID }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ env.PROJECT_ID }}

      - name: Set environment variables
        run: |
          echo "GCR_REPO=gcr.io/$PROJECT_ID" >> $GITHUB_ENV
          echo "SERVICE_ACCOUNT_EMAIL=$SERVICE_ACCOUNT_NAME@$PROJECT_ID.iam.gserviceaccount.com" >> $GITHUB_ENV
          echo "IMAGE_PLANET=gcr.io/$PROJECT_ID/planet-demo:v1" >> $GITHUB_ENV
          echo "IMAGE_PLANET_ADMIN=gcr.io/$PROJECT_ID/planet-demo-admin:v1" >> $GITHUB_ENV

      - name: Configure Docker authentication for GCR
        run: gcloud auth configure-docker

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Build and push regular image using GitHub cache
      - name: Build and push regular image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./docker/Dockerfile
          push: true
          tags: ${{ env.IMAGE_PLANET }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # Build and push admin image using GitHub cache
      - name: Build and push admin image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./docker/Dockerfile
          push: true
          tags: ${{ env.IMAGE_PLANET_ADMIN }}
          build-args: |
            APP_MODE=admin
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # Deploy regular service to Cloud Run
      - name: Deploy regular service to Cloud Run
        run: |
          gcloud run deploy planet-stanford \
            --image="${IMAGE_PLANET}" \
            --platform=managed \
            --region="${REGION}" \
            --allow-unauthenticated \
            --service-account="${SERVICE_ACCOUNT_EMAIL}"

      # Deploy admin service to Cloud Run
      - name: Deploy admin service to Cloud Run
        run: |
          gcloud run deploy planet-stanford-admin \
            --image="${IMAGE_PLANET_ADMIN}" \
            --platform=managed \
            --region="${REGION}" \
            --allow-unauthenticated \
            --service-account="${SERVICE_ACCOUNT_EMAIL}"