name: Deploy to Cloud Run

on:
  push:
    branches:
      - main  # Or your main branch name

env:
  PROJECT_ID: "premium-state-449406-n8"
  REGION: "us-east1"
  SERVICE_ACCOUNT_NAME: "gh-cicd-agent"

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set environment variables
        run: |
          echo "GCR_REPO=gcr.io/$PROJECT_ID" >> $GITHUB_ENV
          echo "SERVICE_ACCOUNT_EMAIL=$SERVICE_ACCOUNT_NAME@$PROJECT_ID.iam.gserviceaccount.com" >> $GITHUB_ENV
          echo "IMAGE_PLANET=$GCR_REPO/planet-demo:v1" >> $GITHUB_ENV
          echo "IMAGE_PLANET_ADMIN=$GCR_REPO/planet-demo-admin:v1" >> $GITHUB_ENV

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ env.PROJECT_ID }}
          version: 'latest'

      - name: Configure Docker authentication
        run: gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev

      - name: Build and push Docker images
        run: |
          docker build -t "${{ env.IMAGE_PLANET }}" -f docker/Dockerfile .
          docker build --build-arg APP_MODE=admin -t "${{ env.IMAGE_PLANET_ADMIN }}" -f docker/Dockerfile .
          docker push "${{ env.IMAGE_PLANET }}"
          docker push "${{ env.IMAGE_PLANET_ADMIN }}"

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy planet-stanford \
            --image="${{ env.IMAGE_PLANET }}" \
            --platform=managed \
            --region="${{ env.REGION }}" \
            --allow-unauthenticated \
            --service-account="${{ env.SERVICE_ACCOUNT_EMAIL }}"

          gcloud run deploy planet-stanford-admin \
            --image="${{ env.IMAGE_PLANET_ADMIN }}" \
            --platform=managed \
            --region="${{ env.REGION }}" \
            --allow-unauthenticated \
            --service-account="${{ env.SERVICE_ACCOUNT_EMAIL }}"
